### ISSUE TITLE
lra is not found

### ISSUE THREAD

**Issue by Xi-yuanWang** [OpenNLPLab/Transnormer#1]
@Doraemonzzz Hello, I am trying to reproduce the experiments. However, I find that LRA experiments need https://github.com/OpenNLPLab/lra.gits, which is not found. Could you please release it? Thank you.

**Comment by Doraemonzzz** [comment]
Sorry, it's a typo, the link is `https://github.com/OpenNLPLab/lra.git`, I have fixed it.

**Comment by Xi-yuanWang** [comment]
Thank you. But I cannot find run_task.sh in lra.

**Comment by Xi-yuanWang** [comment]
@Doraemonzzz

**Comment by Doraemonzzz** [comment]
Sorry, I missed this message, now typo has been fixed.
