### ISSUE TITLE
multiprocess error

### ISSUE THREAD

**Issue by Xi-yuanWang** [OpenNLPLab/Transnormer#2]
Hello, I have the following error when running train_alm.sh with the environment in env1.yaml. Could you please help me?

Traceback (most recent call last):
  File "/home/wangxiyuan/miniconda3/envs/transnormer/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/data1/wangxiyuan/Transnormer/fairseq/fairseq_cli/train.py", line 502, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/data1/wangxiyuan/Transnormer/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/data1/wangxiyuan/Transnormer/fairseq/fairseq_cli/train.py", line 123, in main
    trainer = Trainer(cfg, task, model, criterion, quantizer)
  File "/data1/wangxiyuan/Transnormer/fairseq/fairseq/trainer.py", line 143, in __init__
    if self.data_parallel_rank == 0:
  File "/data1/wangxiyuan/Transnormer/fairseq/fairseq/trainer.py", line 176, in data_parallel_rank
    return distributed_utils.get_data_parallel_rank()
  File "/data1/wangxiyuan/Transnormer/fairseq/fairseq/distributed/utils.py", line 463, in get_data_parallel_rank
    return get_rank(get_data_parallel_group())
  File "/data1/wangxiyuan/Transnormer/fairseq/fairseq/distributed/utils.py", line 405, in get_rank
    return dist.get_rank(group=group)
  File "/home/wangxiyuan/miniconda3/envs/transnormer/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 688, in get_rank
    default_pg = _get_default_group()
  File "/home/wangxiyuan/miniconda3/envs/transnormer/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by Doraemonzzz** [comment]
It seems to be a problem with multi-gpu initialization. You can try to set the number of gpus to 1 first, and then see if an error will be reported.

**Comment by Xi-yuanWang** [comment]
This error will not happen with 1 GPU.

**Comment by Doraemonzzz** [comment]
What is your local environment, could you please execute `nvidia-smi`?

**Comment by Xi-yuanWang** [comment]
8x3090
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:00:07.0 Off |                  N/A |
| 85%   68C    P2   333W / 350W |  23688MiB / 24576MiB |     95%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:00:08.0 Off |                  N/A |
| 52%   24C    P8    21W / 350W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:00:09.0 Off |                  N/A |
| 54%   31C    P8    23W / 350W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  Off  | 00000000:00:0A.0 Off |                  N/A |
| 30%   23C    P8    18W / 350W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  Off  | 00000000:00:0B.0 Off |                  N/A |
| 53%   58C    P2   246W / 350W |   6546MiB / 24576MiB |     59%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce ...  Off  | 00000000:00:0C.0 Off |                  N/A |
| 30%   26C    P8    20W / 350W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce ...  Off  | 00000000:00:0D.0 Off |                  N/A |
| 50%   25C    P8    26W / 350W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce ...  Off  | 00000000:00:0E.0 Off |                  N/A |
| 34%   27C    P8    23W / 350W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A     46885      C   ...vs/transnormer/bin/python    23680MiB |
|    1   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
|    4   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
|    4   N/A  N/A     47301      C   ...vs/transnormer/bin/python     6538MiB |
|    5   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
|    6   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
|    7   N/A  N/A      2063      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

**Comment by Doraemonzzz** [comment]
It seems that there is no problem, I will test the code again and reply to you later.

**Comment by sjtuzzw** [comment]
I have the same problem.

**Comment by Doraemonzzz** [comment]
Could you provide the training script and error log?

**Comment by sjtuzzw** [comment]
Traceback (most recent call last):
  File "/root/miniconda3/envs/transnormer/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/nfs/my/code/fairseq-evo/fairseq_cli/train.py", line 502, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/nfs/my/code/fairseq-evo/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/nfs/my/code/fairseq-evo/fairseq_cli/train.py", line 123, in main
    trainer = Trainer(cfg, task, model, criterion, quantizer)
  File "/nfs/my/code/fairseq-evo/fairseq/trainer.py", line 143, in __init__
    if self.data_parallel_rank == 0:
  File "/nfs/my/code/fairseq-evo/fairseq/trainer.py", line 176, in data_parallel_rank
    return distributed_utils.get_data_parallel_rank()
  File "/nfs/my/code/fairseq-evo/fairseq/distributed/utils.py", line 463, in get_data_parallel_rank
    return get_rank(get_data_parallel_group())
  File "/nfs/my/code/fairseq-evo/fairseq/distributed/utils.py", line 405, in get_rank
    return dist.get_rank(group=group)
  File "/root/miniconda3/envs/transnormer/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 688, in get_rank
    default_pg = _get_default_group()
  File "/root/miniconda3/envs/transnormer/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by sjtuzzw** [comment]
bash train_alm.sh 2 transnormer_t1 /root/code/fairseq-evo/data-bin/wikitext-103

**Comment by Doraemonzzz** [comment]
I have reproduced the issue and will get back to you when it is fixed.

**Comment by sjtuzzw** [comment]
Thanks！！

**Comment by Doraemonzzz** [comment]
The problem can be solved by removing the parameter `--distributed-port $PORT`, I have updated the readme, the previous script works for slurm cluster. If you have more questions, please feel free to ask.

**Comment by sjtuzzw** [comment]
Thanks for your reply!
